### ISSUE TITLE
Feld für die englische Übersetzung der Position auf der Teamseite

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#11]

**Comment by stadine** [comment]
<img width="1246" alt="bildschirmfoto 2018-12-13 um 16 28 27" src="https://user-images.githubusercontent.com/7421063/49948671-30dc0100-fef4-11e8-9b21-be0ac774df6f.png">

**Comment by lislis** [comment]
Das Template erwarted jetzt `position_en` in der team.yml. Wenn das leer ist wird es einfach nicht angezeigt.
Beispiel https://github.com/okfde/okfde-reloaded/blob/9f030e5499284df59f78b426ea017786e490ee37/data/team.yaml#L809

**Comment by stadine** [comment]
hab die beschreibungen bei allen hinzugefügt
