### ISSUE TITLE
Bildgrößen verkleinern

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#12]
nicht größer als 100kb

**Comment by lislis** [comment]
Max 200kB
- [x] edulabs tile + header
- [x] openSchufa tile + header
- [x] turing bus tile + header
- [x] frag den staat
- [x] demolabs

Max 180KB
- [x] bela
- [x] juliane
- [x] philip  steffan
- [x] doris
- [x] jasmin
- [x] NadinE
- [x] Paula
- [x] Walter

themen max 200kb
- offene bildung
- if
- ciciv tehc
- open data

profil max 300kb
- profil 3
- profil 6

**Comment by stadine** [comment]
done
