### ISSUE TITLE
Doppelte Vergabe von Kategorien für Projekte

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#2]

**Comment by lislis** [comment]
bei welchen Projekten hast du die doppelte vergabe versucht? Sind die noch irgendwo?

**Comment by stadine** [comment]
es kann sein, dass ich sie wieder rausgenommen hatte. aber wenn ich z.b. bei edulabs die kategorien „community“ und „bildung“ vergebe, erscheint das projekt nach auswahl der filter nicht mehr. 
ich pushe es nachher mal, bekomme aber keine fehlermeldung, dass im yaml etwas falsch ist

**Comment by lislis** [comment]
done in 2d48f14eeaf9d0ab7ae2d9c2e293bb865308dbaa
