### ISSUE TITLE
Logo Initiative Transparente Zivilgesellschaft im Footer

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#20]
mit Link. unter die Social Media Icons

**Comment by lislis** [comment]
Sieht jetzt so aus
![screenshot from 2019-01-02 12-21-26](https://user-images.githubusercontent.com/1006478/50589976-22489000-0e89-11e9-9d66-58d3b06520c8.png)

**Comment by lislis** [comment]
Jetzt mit hover
