### ISSUE TITLE
Finanzseite

### ISSUE THREAD

**Issue by DiniOkf** [okfde/okfn.de#22]
Downloads: 
- Wirtschaftsprüfung und Lagebericht kommen erst im Mai/Juni zum ersten Mal
- hier muss noch der aktuelle Freistellungsbescheid vom Finanzamt rein
- die Gewinn- und Verlustrechnung müss für alle Jahre hier abgelegt werden

**Comment by stadine** [comment]
Freistellungsbescheid sowie die Gewinn- und Verlustrechnung habe ich für alle Jahre zur Download-Section hinzugefügt. 

<img width="1191" alt="bildschirmfoto 2019-01-08 um 12 36 00" src="https://user-images.githubusercontent.com/7421063/50828547-fbcf9c80-1341-11e9-88cf-dceea0899a59.png">
