### ISSUE TITLE
Falsche Angabe der Einnahmen öffentlicher Gelder in %

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#35]
<img width="971" alt="bildschirmfoto 2019-01-22 um 13 06 01" src="https://user-images.githubusercontent.com/7421063/51534612-80441400-1e46-11e9-93d5-a46003b2a08b.png">

Die Angabe der Prozentzahl zu den Gesamteinnahmen im Hover scheint falsch zu schein.

- laut der Grafik sind es ca. 9%; im Hover sind es 17%
- sieht so aus als wird die Grafik abgeschnitten

**Comment by lislis** [comment]
Ja, das ist tatsächlich seltsam. Die 17% sind richtig berechnet aber die Skala geht nicht mit, was bei allen anderen aber funktioniert. Bin noch etwas planlos deswegen :thinking:

**Comment by lislis** [comment]
Done 5f5de6b631493d4edda4be0e7ed53d4db0170147
