### ISSUE TITLE
Project-Teaser-Tile Error Error

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#36]
<img width="362" alt="bildschirmfoto 2019-01-22 um 12 49 06" src="https://user-images.githubusercontent.com/7421063/51535020-a61de880-1e47-11e9-9a7e-9fd86223a6ae.png">

+ wenn die überschrift über zwei zeilen läuft
+ kann die überschrift auf weiß werden?

**Comment by lislis** [comment]
done in 41d35781e942156f38e9791f047be8c308186f38
