### ISSUE TITLE
Projektteaser auf Startseite

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#37]
<img width="499" alt="bildschirmfoto 2019-01-22 um 17 03 06" src="https://user-images.githubusercontent.com/7421063/51548016-b1810c00-1e67-11e9-96c2-649d5c5fe669.png">

+ wäre super, wenn sich die Projektteaser auf der Startseite mobil gleich verhalten, wie in der Desktopversion – grade werden auch große Teaser zu kleinen Teasern
+ sie sollten den selben Hover haben wie auf der Projektübersicht

**Comment by lislis** [comment]
done in 428cc7ff13ff51121b1e7fe289930e923016e76e
