### ISSUE TITLE
Bilder auf Projektdetailseite

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#38]
+ verrutscht
+ waren mal zentriert

<img width="1440" alt="bildschirmfoto 2019-01-22 um 17 15 16" src="https://user-images.githubusercontent.com/7421063/51548836-7253ba80-1e69-11e9-83bc-c9d0cb8ff4be.png">

**Comment by lislis** [comment]
Wie meinst du ''zentriert"? War das nicht so ein bisschen 'off-grid' gedacht?

**Comment by stadine** [comment]
Ja, ich dachte, das müsste in der project.html passieren und hatte es nicht gefunden. Ist jetzt drin.
