### ISSUE TITLE
Lizenzangabe für Bilder 

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#39]
😬

**Comment by stadine** [comment]
<img width="1199" alt="bildschirmfoto 2019-01-22 um 18 23 29" src="https://user-images.githubusercontent.com/7421063/51553364-eb0b4480-1e72-11e9-985b-57e3f1603b01.png">

**Comment by lislis** [comment]
Passiert das jetzt nur beim hover oder immer so?
Und: das kommt jetzt auf alle Bilder außer Blog, richtig?
Und: sind die Lizenzangaben für alle Bilder irgendwo vermerkt?

**Comment by stadine** [comment]
+ nur beim hover
+ wenn es nicht viel mehr stress ist, auch bei bei bildern im blog
+ die meisten bilder habe ich aus flickr. ich würde die morgen raussuchen und eintragen. oder möchtest du das vorab haben? meintest du das?

**Comment by lislis** [comment]
Startseite, profil, projekte, blog und Querverlinkungskästen

**Comment by lislis** [comment]
Markup für Lizenzen ist vorbereitet.
generell sieht das so aus:
```html
<figure class="license">
    <img src="/path/to/img.jpg" alt="" >
    <figcaption>Foto: author, werk, lizenz</figcaption>
</figure>
```
Auf den Projektseiten ist das im HTML einfach so einfügbar. Aktuelle Projekte und Weitere Projekte habe ich schon vorbereitet (fehlen die urls und lizenzen), abgeschlossene Projekte fehlen noch.

Im Yaml was vorher so aussah:
```yaml
img:
  - /path/to/img.png
```

wird jetzt zu:
```yaml
img:
  - 
    url: /path/to/img.png
    license: 'Wenn : oder HTML vorkommt, dann in Anfuerungszeichen'
```
Edit: es scheint bei doppelten Anf[hrungszeigen in HTML in  `license` dann probleme beim JSON parsing im such index zu geben. Meh. Wenn dann einfache Anführungszeichen benutzen

Auch vorbereitet: startseite, profil, jobs, 404, projekte wie erwähnt

Zu Blog: Hier have ich die alten Felder uebernommen,  `image.src`, `image.title`, `image.license` und `image.license_url` koennen separat angegeben werden

**Comment by lislis** [comment]
OMG, done!
