### ISSUE TITLE
kaputtes Teaserbild auf Profilseite in Chrome

### ISSUE THREAD

**Issue by stadine** [okfde/okfn.de#4]
in Chrome Version 70.0.3538.

<img width="976" alt="bildschirmfoto 2018-12-04 um 18 36 00" src="https://user-images.githubusercontent.com/7421063/49461245-811bda80-f7f3-11e8-9f66-d7be75311a2b.png">

**Comment by lislis** [comment]
done in b447818d355f9792acd047e6c6f4d5f9417e68a0
