### ISSUE TITLE
Taxonomy URLs

### ISSUE THREAD

**Issue by stefanw** [okfde/okfn.de#52]
Offenbar funktionierten die alten Tag-URLs nicht mehr:

Alt: https://okfn.de/blog/tags/praktikant/
War neu: https://okfn.de/tags/praktikant/

Ich habe jetzt in der config.toml was geändert:
```
[permalinks]
  tags = 'blog/tags/:slug/'
```

Ggf. müssen wir das auch für Kategorien-Seiten machen (falls wir die vorher hatten).

**Comment by lislis** [comment]
Ah guter Punkt, danke für's fixen. Kategorien-Seiten hatten wir vorher nicht (zumindest nicht soweit ich das gesehen habe), das sollte also ok sein

**Comment by lislis** [comment]
Oder meinst du die Projektkategorien (im Gegensatz zu Blogkategorien)? Die gab es vorher auch nicht, läuft also auch
