### ISSUE TITLE
Some meta tag icons are 404

### ISSUE THREAD

**Issue by stefanw** [okfde/okfn.de#54]

**Comment by lislis** [comment]
Do you have an example url?

**Comment by lislis** [comment]
I found https://okfn.de/files/favicon/apple-touch-icon.png was actually missing but I found /apple-icon.png instead, I assume that the icon generator has a bug where the path is wrong? Anyway, fix coming up in 9ca6e6db6c9c839d6fec34a84d49a5dd041186be
I'm closing this, feel free to reopen if there is another case of this
