### ISSUE TITLE
Make project titles on images always visible

### ISSUE THREAD

**Issue by jfilter** [okfde/okfn.de#62]
![Screen Shot 2019-05-08 at 22 26 11](https://user-images.githubusercontent.com/3450307/57410369-eb91d600-71ea-11e9-9233-a33104a895ea.png)

https://okfn.de/themen/open_data/

Also on `OpenSchufa` and `edulabs` the project title is hard to read.

**Comment by lislis** [comment]
Was done in 1f5083e0131db20c8f7e425288e28cdcf4db4fcc and fb136123350eef0fa54cbc661db5d48625348ad0
