### ISSUE TITLE
EditorConfig

### ISSUE THREAD

**Issue by jfilter** [okfde/okfn.de#63]
What about an `.editorconfig` to prevent unwanted changes due to (auto-)formatting?

https://editorconfig.org/

**Comment by lislis** [comment]
Yeah maybe :thinking: Do you already have some pain points where you'd like to have in there?

**Comment by jfilter** [comment]
On the other hand: if people commit blog posts via GitHub, it won't work anyhow. So yeah, let's keep it like this.

I had problems because I normally automatically format code on save.
