### ISSUE TITLE
Prevent linebreaks between URL and arrow

### ISSUE THREAD

**Issue by jfilter** [okfde/okfn.de#64]
![Screen Shot 2019-05-09 at 00 05 31](https://user-images.githubusercontent.com/3450307/57411552-38c37700-71ee-11e9-91c0-e132823a4229.png)

Found here: https://okfn.de/projekte/demokratielabore/

**Comment by lislis** [comment]
done in ba6946660597f443e0e49f16805a8a41f27760ae
